// Define the mapping of LaTeX symbols to Unicode characters
const latexToUnicode: Record<string, string> = {
  // Lowercase Greek letters
  "\\alpha": "α",
  "\\beta": "β",
  "\\gamma": "γ",
  "\\delta": "δ",
  "\\epsilon": "ε",
  "\\varepsilon": "ε",
  "\\zeta": "ζ",
  "\\eta": "η",
  "\\theta": "θ",
  "\\vartheta": "ϑ",
  "\\iota": "ι",
  "\\kappa": "κ",
  "\\lambda": "λ",
  "\\mu": "μ",
  "\\nu": "ν",
  "\\xi": "ξ",
  "\\omicron": "ο",
  "\\pi": "π",
  "\\varpi": "ϖ",
  "\\rho": "ρ",
  "\\varrho": "ϱ",
  "\\sigma": "σ",
  "\\varsigma": "ς",
  "\\tau": "τ",
  "\\upsilon": "υ",
  "\\phi": "φ",
  "\\varphi": "ϕ",
  "\\chi": "χ",
  "\\psi": "ψ",
  "\\omega": "ω",

  // Uppercase Greek letters
  "\\Alpha": "Α",
  "\\Beta": "Β",
  "\\Gamma": "Γ",
  "\\Delta": "Δ",
  "\\Epsilon": "Ε",
  "\\Zeta": "Ζ",
  "\\Eta": "Η",
  "\\Theta": "Θ",
  "\\Iota": "Ι",
  "\\Kappa": "Κ",
  "\\Lambda": "Λ",
  "\\Mu": "Μ",
  "\\Nu": "Ν",
  "\\Xi": "Ξ",
  "\\Omicron": "Ο",
  "\\Pi": "Π",
  "\\Rho": "Ρ",
  "\\Sigma": "Σ",
  "\\Tau": "Τ",
  "\\Upsilon": "Υ",
  "\\Phi": "Φ",
  "\\Chi": "Χ",
  "\\Psi": "Ψ",
  "\\Omega": "Ω",

  // Common math operations and symbols
  "\\pm": "±",
  "\\mp": "∓",
  "\\times": "×",
  "\\div": "÷",
  "\\cdot": "·",
  "\\bullet": "•",
  "\\oplus": "⊕",
  "\\ominus": "⊖",
  "\\otimes": "⊗",
  "\\oslash": "⊘",
  "\\odot": "⊙",
  "\\circ": "∘",
  "\\ast": "∗",
  "\\star": "⋆",
  "\\diamond": "⋄",
  "\\triangle": "△",
  "\\triangledown": "▽",
  "\\bigtriangleup": "△",
  "\\bigtriangledown": "▽",
  "\\square": "□",
  "\\blacksquare": "■",
  "\\lozenge": "◊",
  "\\blacklozenge": "⧫",

  // Relations
  "\\leq": "≤",
  "\\le": "≤",
  "\\geq": "≥",
  "\\ge": "≥",
  "\\neq": "≠",
  "\\ne": "≠",
  "\\equiv": "≡",
  "\\approx": "≈",
  "\\sim": "∼",
  "\\simeq": "≃",
  "\\cong": "≅",
  "\\propto": "∝",
  "\\parallel": "∥",
  "\\perp": "⊥",
  "\\in": "∈",
  "\\notin": "∉",
  "\\subset": "⊂",
  "\\supset": "⊃",
  "\\subseteq": "⊆",
  "\\supseteq": "⊇",
  "\\cap": "∩",
  "\\cup": "∪",
  "\\setminus": "∖",
  "\\emptyset": "∅",
  "\\varnothing": "∅",

  // Arrows
  "\\rightarrow": "→",
  "\\to": "→",
  "\\leftarrow": "←",
  "\\gets": "←",
  "\\leftrightarrow": "↔",
  "\\Rightarrow": "⇒",
  "\\Leftarrow": "⇐",
  "\\Leftrightarrow": "⇔",
  "\\uparrow": "↑",
  "\\downarrow": "↓",
  "\\updownarrow": "↕",
  "\\Uparrow": "⇑",
  "\\Downarrow": "⇓",
  "\\Updownarrow": "⇕",

  // Calculus and analysis
  "\\partial": "∂",
  "\\nabla": "∇",
  "\\int": "∫",
  "\\iint": "∬",
  "\\iiint": "∭",
  "\\oint": "∮",
  "\\sum": "∑",
  "\\prod": "∏",
  "\\coprod": "∐",
  "\\infty": "∞",
  "\\aleph": "ℵ",

  // Logic
  "\\forall": "∀",
  "\\exists": "∃",
  "\\nexists": "∄",
  "\\land": "∧",
  "\\lor": "∨",
  "\\lnot": "¬",
  "\\neg": "¬",
  "\\top": "⊤",
  "\\bot": "⊥",
  "\\vdash": "⊢",
  "\\models": "⊨",

  // Miscellaneous
  "\\therefore": "∴",
  "\\because": "∵",
  "\\angle": "∠",
  "\\measuredangle": "∡",
  "\\sphericalangle": "∢",
  "\\degree": "°",
  "\\prime": "′",
  "\\backprime": "‵",
  "\\hbar": "ℏ",
  "\\ell": "ℓ",
  "\\wp": "℘",
  "\\Re": "ℜ",
  "\\Im": "ℑ",

  // Blackboard bold (common ones)
  "\\mathbb{N}": "ℕ",
  "\\mathbb{Z}": "ℤ",
  "\\mathbb{Q}": "ℚ",
  "\\mathbb{R}": "ℝ",
  "\\mathbb{C}": "ℂ",
  "\\mathbb{P}": "ℙ",
  "\\mathbb{H}": "ℍ",
};

export function formatLabel(s: string) {
  // strip surrounding dollar signs
  if (s.startsWith("$") && s.endsWith("$")) {
    s = s.slice(1, -1);
  }

  // replace common latex symbols with their unicode
  s = s.replace(/\\(?:mathbb\{[A-Z]\}|[a-zA-Z]+)/g, match => {
    return latexToUnicode[match] ?? match;
  });

  // truncate long labels
  s = s.length > 21 ? s.slice(0, 20) + "…" : s;

  return s;
}
